### ISSUE TITLE
Adopt iam-build-tokens

### ISSUE THREAD

**Issue by j3parker** [Brightspace/continuous-professional-development#182]
See https://github.com/Brightspace/iam-build-tokens/issues/191

For things like FRAs, use [this documentation](https://github.com/Brightspace/iam-build-tokens/blob/master/docs/howto-cdn-users.md) specifically.

This will replace the static IAM credentials your CI job is using with a set of temporary tokens which will be rotated every 6 hours.

If you have any concerns, questions, or have a special use-case don't hesitate to reach out.

**Comment by BraydonKains** [comment]
This has been done!
